### ISSUE TITLE
react-hotkeys: hotkeys with double modifier don't work correctly

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#282] opened 2020-01-21 08:06 UTC
E.g. `cmd+shift` triggers already `cmd+shift+z`

https://github.com/greena13/react-hotkeys/issues/263

**Comment by elbotho** [comment] 2023-04-26 14:55
(can't reproduce)

**Comment by Entkenntnis** [comment] 2023-05-23 10:51
closing in favor of #272

**Closed by Entkenntnis** 2023-05-23 10:51 UTC
Labels: bug, hotkeys
