### ISSUE TITLE
SC/MC Exercise: column width calculation is not working correctly

### ISSUE THREAD

**Issue by metzgaria** [edtr-io/edtr-io#305] opened 2020-03-10 19:07 UTC
should render one per line when not enough space
![grafik](https://user-images.githubusercontent.com/26926820/76349549-80cd9180-630a-11ea-9f1b-3fa84d6d3b86.png)
But: 
![grafik](https://user-images.githubusercontent.com/26926820/76349506-701d1b80-630a-11ea-83d5-dff7a008be3f.png)

https://de.serlo.org/154959

**Comment by inyono** [comment] 2020-03-10 19:34
Duplicate of https://github.com/serlo/serlo.org/issues/336

**Closed by inyono** 2020-03-10 19:34 UTC
